name: Compile And Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Compile
        run: bun compile

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.short_sha }}
          name: ${{ steps.vars.outputs.short_sha }}
          generate_release_notes: true
          files: |
            dist/anifiller.min.json
            dist/anifiller.json
